version: '3.8'

services:
    backend:
        container_name: massive-backend
        image: golang:1.20.3
        volumes:
        - ./backend:/go/src/app
        working_dir: /go/src/app
        ports:
        - 33003:33003
        env_file:
        - ./backend/.env.local
        depends_on:
        - mariadb
        command: go run main.go local
    frontend:
        container_name: massive-frontend
        image: node:20.10.0-alpine
        volumes:
        - ./frontend:/app
        working_dir: /app/frontend
        ports:
        - 8080:5173
        env_file:
        - ./frontend/.env.local
        command: npm run local
    mariadb:
        container_name: massive-uploader-mariadb
        image: "mariadb:11.3.1-rc"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=massive
            - MYSQL_USER=massive
            - MYSQL_PASSWORD=root
            - MYSQL_TCP_PORT=3307
        ports:
        - 3307:3307
        volumes: 
        - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
