version: '3.8'

services:
    mariadb:
        container_name: massive-uploader-mariadb
        image: "mariadb:11.3.1-rc"
        restart: unless-stopped
        networks: 
          - massive-uploader-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=massive
            - MYSQL_USER=massive
            - MYSQL_PASSWORD=root
            - MYSQL_TCP_PORT=3307
        ports:
        - 3307:3307
        volumes: 
        - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local

networks:
  massive-uploader-network:
    external:
      name: massive-uploader-network